  # Oracle Linux
  # i386
  quartermaster::pxelinux{'oraclelinux-4.4-i386':}
  quartermaster::pxelinux{'oraclelinux-4.5-i386':}
  quartermaster::pxelinux{'oraclelinux-4.6-i386':}
  quartermaster::pxelinux{'oraclelinux-4.7-i386':}
  quartermaster::pxelinux{'oraclelinux-4.8-i386':}
  quartermaster::pxelinux{'oraclelinux-5.0-i386':}
  quartermaster::pxelinux{'oraclelinux-5.1-i386':}
  quartermaster::pxelinux{'oraclelinux-5.2-i386':}
  quartermaster::pxelinux{'oraclelinux-5.3-i386':}
  quartermaster::pxelinux{'oraclelinux-5.4-i386':}
  quartermaster::pxelinux{'oraclelinux-5.5-i386':}
  quartermaster::pxelinux{'oraclelinux-5.6-i386':}
  quartermaster::pxelinux{'oraclelinux-5.7-i386':}
  quartermaster::pxelinux{'oraclelinux-5.8-i386':}
  quartermaster::pxelinux{'oraclelinux-5.9-i386':}
  quartermaster::pxelinux{'oraclelinux-5.10-i386':}
  quartermaster::pxelinux{'oraclelinux-5.11-i386':}
  quartermaster::pxelinux{'oraclelinux-6.0-i386':}
  quartermaster::pxelinux{'oraclelinux-6.1-i386':}
  quartermaster::pxelinux{'oraclelinux-6.2-i386':}
  quartermaster::pxelinux{'oraclelinux-6.3-i386':}
  quartermaster::pxelinux{'oraclelinux-6.4-i386':}
  quartermaster::pxelinux{'oraclelinux-6.5-i386':}
  quartermaster::pxelinux{'oraclelinux-6.6-i386':}
  quartermaster::pxelinux{'oraclelinux-6.7-i386':}
  quartermaster::pxelinux{'oraclelinux-6.8-i386':}
  quartermaster::pxelinux{'oraclelinux-6.9-i386':}
